/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Accounts {
  createdAt: number;
  id: string;
}

export interface AppliedOps {
  clientOpId: string;
  listId: string;
}

export interface Categories {
  color: string;
  icon: string;
  id: string;
  name: string;
  sort: number;
}

export interface Devices {
  accountId: string;
  createdAt: number;
  id: string;
  token: string;
}

export interface ItemFrequency {
  accountId: string;
  count: Generated<number>;
  normalizedName: string;
}

export interface Items {
  categoryId: string | null;
  checked: Generated<number>;
  deleted: Generated<number>;
  id: string;
  listId: string;
  name: Generated<string>;
  quantity: Generated<number>;
  updatedAt: number;
  version: number;
}

export interface LinkCodes {
  accountId: string;
  code: string;
  expiresAt: number;
}

export interface ListInvites {
  code: string;
  expiresAt: number;
  listId: string;
}

export interface ListMembers {
  accountId: string;
  listId: string;
  role: string;
}

export interface Lists {
  createdAt: number;
  id: string;
  name: string;
  ownerAccountId: string;
  seq: Generated<number>;
}

export interface DB {
  accounts: Accounts;
  appliedOps: AppliedOps;
  categories: Categories;
  devices: Devices;
  itemFrequency: ItemFrequency;
  items: Items;
  linkCodes: LinkCodes;
  listInvites: ListInvites;
  listMembers: ListMembers;
  lists: Lists;
}
